### ISSUE TITLE
Too many arguments, expected arguments "command".

### ISSUE THREAD

**Issue by extjac** [JunaidQadirB/cray#1]
Too many arguments, expected arguments "command" when running php artisan vendor:publish cray generates error
Windows using Xampp for local env.

**Comment by tsarbo** [comment]
I had the same error
I solved it by using
` php artisan vendor:publish --tag=cray`

**Comment by JunaidQadirB** [comment]
@extjac if you type `php artisan vendor:publish` and press enter, you will see a list enter the number corresponding to `cray` or as @tsarbo suggested.

Thanks for reporting the issue. I'll update the readme.
