### ISSUE TITLE
Unresolvable dependency resolving [Parameter #1 [ <required> $customStubPath ]] in class Illuminate\Database\Migrations\MigrationCreator

### ISSUE THREAD

**Issue by cmpengineers** [JunaidQadirB/cray#23]
Hello Junaid

I got this issue with laravel 9.1, PHP 8.1 

`
   Illuminate\Contracts\Container\BindingResolutionException 

  Unresolvable dependency resolving [Parameter #1 [ <required> $customStubPath ]] in class Illuminate\Database\Migrations\MigrationCreator

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:1102
    1098▕     protected function unresolvablePrimitive(ReflectionParameter $parameter)
    1099▕     {
    1100▕         $message = "Unresolvable dependency resolving [$parameter] in class {$parameter->getDeclaringClass()->getName()}";
    1101▕ 
  ➜ 1102▕         throw new BindingResolutionException($message);
    1103▕     }
    1104▕ 
    1105▕     /**
    1106▕      * Register a new before resolving callback for all types.

      +21 vendor frames 
  22  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

**Comment by JunaidQadirB** [comment]
Which version of cray are you using.

I couldn't reproduce the error `jq/cray:3.2.0-beta5`

To install `jq/cray:3.2.0-beta5`, run in your Laravel project directory:

```bash
composer require "jq/cray:3.2.0-beta5" --dev
```
