### ISSUE TITLE
Dont Work Package

### ISSUE THREAD

**Issue by ghost** [JunaidQadirB/cray#24]
Laravel Version => 9x
Php Version => 8x

![resim](https://user-images.githubusercontent.com/64495914/174235797-1055bec7-2e11-445d-895c-bf7c4e15491d.png)

**Comment by JunaidQadirB** [comment]
You are using an old version of `Cray`. Please use version `3.2.0-beta5`

To install it, run:

```bash
composer require "jq/cray:3.2.0-beta5" --dev
```
