### ISSUE TITLE
Tailwind CSS support

### ISSUE THREAD

**Issue by azeemhassni** [JunaidQadirB/cray#4]
It would be great to see Livewire+TailwindCSS support in cray, and also configurable views directory would be a great plus. 

Thanks for your work on this. 👏

**Comment by JunaidQadirB** [comment]
Thanks!

In `v3.2.0-beta2` when running `php artisan cray Modelname`, the user gets a prompt to choose the target for generating views if you have provided multiple view paths in `config/view.php`

As you can customize the provided stubs, you can use any UI kit. But for now we don't offer built-in support for Tailwind. May be in future we do add the option to choose a preset just like Laravel does.

**Comment by rakeshappycodes** [comment]
**Tailwind** support will save lots of time.
